/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Blinking LED (8-LED) [0-7]
 *
 * */
#include <stdint.h>
 // simple delay
void delay(void)
{
	for(volatile uint32_t i=0; i<3000; i++);
}

int main(void)
{
	// RCC  Base Address = 0x4002 3800 Address offset: 0x30 [0x4002 3800 + 0x30 =  0x40023830]
	uint32_t *portcAHB1ENR = (uint32_t*)0x40023830;

	// Base Address = 0x40020000
	uint32_t *portcMODER   = (uint32_t*)0x40020800;

	// Base Address = 0x40020000 >> Address offset: 0x14  [0x4002 0000 + 0x14 =  0x40020014]
	uint32_t *portcODR     = (uint32_t*)0x40020814;

	*portcAHB1ENR |= (1<<2);
	*portcMODER &= 0xFFFF0000;
	*portcMODER |= 0x00005555;
//	*MODER |=0x00000400;

	while(1)
	{
		*portcODR |= 0x80;
		delay();
		for( uint32_t i=0; i<3000; i++)
		{
			*portcODR = (*portcODR << 1); // shift one time to left
			delay();
		}
	}
}
